# Pulling nodejs base image
FROM node:12-alpine

RUN apk --no-cache add git make python curl
RUN apk add --virtual build-dependencies build-base gcc
WORKDIR /app

RUN npm install -g nodemon
RUN npm install -g wait-on

CMD [ "sh", "bin/run.sh" ]
